# fly.toml app configuration file generated for tesero-sol on 2024-06-28T15:51:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tesero-sol'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '150GB'
  cpu_kind = 'performance'
  cpus = 4
